Step 2
kulich51/graduate_work_command_4 pull request #2
Opened 2022-08-01 16:32 UTC by kulich51

2022-08-08 10:27 UTC, OlgaLugacheva requested changes

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/WebSecurityConfig.java
> +//                Эта строка мешают CORS
хм , очень странно, пока не могу сказать почему

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/WebSecurityConfig.java
> +    public JdbcUserDetailsManager jdbcDetailsService() {
до этого пока рановато

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/dto/FullAdsDto.java
> +//    private final String description;
в задании указано, что поля могут быть пропущены в выданной в задании схеме, поэтому если где-то полей не хватает - добавляйте.

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/entity/Ads.java
> +    private Long author;
точно ли тут нет никаких связей между таблицами - подумайте об этом и при необходимлсти произведите изменения

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/repository/CommentRepository.java
> +    Comment getByAdsIdAndId(Long adsId, Long commentId);
Может быть Optional ?

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/repository/UserProfileRepository.java
> +    UserProfile getById(Long id);
зачем это, если эти методы есть в родителях? 
по-моему, надо удалить

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/repository/AdsRepository.java
> +    Optional<Ads> findById(Long adsId);
зачем, если есть в родителе?

2022-08-08 10:27 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/AuthServiceImpl.java
> +//        userProfileRepository.save(userProfile);
да, не передаются, но мы можем их обновить через другую форму

2022-08-08 16:16 UTC, kulich51 commented on src/main/java/ru/skypro/homework/WebSecurityConfig.java
> +    public JdbcUserDetailsManager jdbcDetailsService() {
Как тогда пользователей в БД сохранять?

2022-08-09 16:25 UTC, kulich51 commented on src/main/java/ru/skypro/homework/service/impl/AuthServiceImpl.java
> +//        userProfileRepository.save(userProfile);
ok

2022-08-09 17:32 UTC, OlgaLugacheva approved these changes

2022-08-10 12:25 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/WebSecurityConfig.java
> +    public JdbcUserDetailsManager jdbcDetailsService() {
тут все верно, я к тому что пока мы это не проверяем))

2022-08-16 16:06 UTC, merged