Step 5
kulich51/graduate_work_command_4 pull request #8
Opened 2022-08-26 18:14 UTC by kulich51

2022-08-27 09:39 UTC, OlgaLugacheva requested changes

2022-08-27 09:39 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +    ResponseEntity<AdsDto> createAds(@ModelAttribute CreateAds ads, Authentication authentication) {
давайте тут исправим на 
```
    public ResponseEntity<AdsDto> createAds(@RequestPart("properties") @Valid @NotNull @NotBlank CreateAds ads,
                                         @RequestPart("image") @Valid @NotNull @NotBlank MultipartFile file) {
```

с текущей реализацией клиента иначе не будут картинки сохраняться

2022-08-27 09:39 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/dto/AdsDto.java
> +    private final byte[] image;
нет, именно String

2022-08-27 09:39 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
не хватает эндпоинта для выгрузки картинки, вроде такого 


    @GetMapping(value = "/api/{id}/image", produces = {MediaType.IMAGE_PNG_VALUE})
    public ResponseEntity<byte[]> getAdsAvatar(@PathVariable("id") String id) {

2022-09-02 08:59 UTC, OlgaLugacheva requested changes

2022-09-02 08:59 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/dto/CreateAds.java
>      private final int price;
не хватает  поля String description;

2022-09-02 08:59 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +        Comment comment = commentRepository.getByAdsIdAndId(adsId, commentId).get();
get() всегда избегат, это потенциально опасно- здесь и везде заменить на orElseThrow()

2022-09-02 08:59 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +    private static String SOURCE_URL = "http://127.0.0.1:8080/";
это можно уже убрать - фронт должен отрабатывать нормально с картинками

2022-09-02 08:59 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/AuthServiceImpl.java
> +        UserProfile userProfile = new UserProfile();
сейчас все поля предаются, поэтому можно вннесим их в dto 

    private String firstName;
    private String lastName;
    private String phone;

2022-09-02 08:59 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +            e.printStackTrace();
тогда уж логгер

2022-09-02 08:59 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +        LocalDateTime now = LocalDateTime.now();
можно inline

2022-09-02 08:59 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +        fullAds.setImage(SOURCE_URL + ads.getImage().getId().toString());
вместо SOURCE_URL можно оставить "/"

2022-09-02 14:47 UTC, kulich51 commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +    private static String SOURCE_URL = "http://127.0.0.1:8080/";
При просмотре полной информации об объявлении (FullAdsDto) картинки без этой строки не видно

2022-09-02 15:07 UTC, kulich51 commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +        fullAds.setImage(SOURCE_URL + ads.getImage().getId().toString());
Без SOURCE_URL в FullAds картинки не будет видно

2022-09-02 15:07 UTC, merged